### ISSUE TITLE
Organisation listing must be accessible in a common location

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#10]
### Current behaviour

Once you click **Add Certificates** in the mobile app, the user will be shown organisation listing. Once the user clicks an organisation he will be able to see the certificates types the organisation is offering.

### Proposed behaviour

Organisation listing should be shown in the first activity when the app opens or from a dedicated organisation listing page. This allows you to group all the organisation related transactions.

Once the user clicks an organisation from the listing, he should be able to see the following

1. Data exchange requests (initiated by a connected organisation, for e.g. Your personal bank requests to share employment details for processing loan application while you are sitting at home)
2. Consent requests (TBD)
3. Data types offered by the organisation (for e.g. COVID19 test results, National ID, Shopping bills e.t.c)

**Comment by darkchylde** [comment]
@josmilan @lalc Do use this issue to share your thoughts. This is for enhancing user experience within the app and will be prioritized after basic functionalities are integrated into the app.

**Comment by lalc** [comment]
This is super! Very similar to Apple wallet
