### ISSUE TITLE
Progress indicator on data exchange

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#25]
Show a progress indicator when the user clicks exchange data. (Wait until an acknowledgement from verifier agent).

This behaviour seems appropriate than immediately exiting from exchange data screen on clicking exchange.

**Comment by darkchylde** [comment]
You can wait until a timeout period (for e.g 10 seconds), If not received acknowledgment by then, you can show a toast, indicating to the user that "Data exchange taking longer than expected" and move to the home page.

**Comment by josmilan** [comment]
Can you elaborate on what is the current issue?

**Comment by darkchylde** [comment]
@josmilan Don't add to be checked label. I have moved the issue to To be checked deck
