### ISSUE TITLE
QR code scan page color scheme should match with rest

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#27]
The color scheme should be the same as other pages within the app.
![Screenshot_20201222-055541](https://user-images.githubusercontent.com/16397960/102834624-9552c480-441a-11eb-8ec1-8df7fa7a4e61.png)

**Comment by josmilan** [comment]
Can you give a small description of the same. Like what color should be given and changes needed

**Comment by darkchylde** [comment]
@josmilan Can we reuse the design iGrant.io demo app?

**Comment by darkchylde** [comment]
@josmilan I have attached a reference image. The background should be transparent as in iGrant.io app.
