### ISSUE TITLE
Requested data is not fetched properly in data exchange

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#43]
### Scenario

On data exchange request, the requested is not fetched, even when there is stored credential available with requested data.

Reference video attached for better context.

Note: This issue might be in relation with #12 

https://user-images.githubusercontent.com/16397960/102833805-296f5c80-4418-11eb-9a97-81e740fe0407.mp4

**Comment by josmilan** [comment]
couldn't replicate the issue
@darkchylde please guide me to replicate the same
