### ISSUE TITLE
Screen workflow improvement

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-android#53]
On accepting the data agreement, the user shall be taken to the main screen.

Also, please modify the screen as shown

![Preview_of_offered_data_(lal)](https://user-images.githubusercontent.com/455274/103682062-a3f7ba80-4f88-11eb-94c4-9a33ef85286e.png)

**Comment by josmilan** [comment]
HI, @lalc it will feel like a close button. What do you think?

**Comment by josmilan** [comment]
replacing cross icon with bin icon
