### ISSUE TITLE
No option to add a connection

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-android#65]
Went to org screeen and the couldnt find option to add a new connection. 

Noticed that the reason why the + button disappeared is because its white in color against a white/off-white background

**Comment by josmilan** [comment]
It Will not be an issue after changing the org list screen 
issue #64

**Comment by lalc** [comment]
Agree. Pls close this issue

**Comment by josmilan** [comment]
ok
