### ISSUE TITLE
Missing cancel button when searching

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-android#66]
There is no option to cancel the keyboard search option. The only option is to close the app and reopen

**Comment by josmilan** [comment]
It won't be there for the android app, since it is the default in the iOS app. In android it is not like that, If it needed then we have to customize the search

**Comment by lalc** [comment]
We need a possibility to cancel the keyboard pop up. How do they do it normally in android?

**Comment by josmilan** [comment]
In android we have a back button, that is the user mostly uses. Also, we can add a done button in the keyboard to dismiss the keyboard
