### ISSUE TITLE
Data wallet settings page.

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#7]
A settings page should be provided in the app. It should be displaying the following,

1. Wallet name
2. Ledger URL
3. App version
4. Language (default to English)

Note: This will be an initial version, will be further expanded with enhanced functionalities.

**Comment by lalc** [comment]
I am assuming it’s in the settings page there will be an option to choose different ledgers. Default is our own ledger

**Comment by darkchylde** [comment]
> I am assuming it’s in the settings page there will be an option to choose different ledgers. Default is our own ledger

Yes.
