### ISSUE TITLE
Remove the text from connection dialogue

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#78]
Remove the current text "Allow <org name> to connect with you" from the connection dialogue which is shown on trying to connect to an organisation

![2021-01-25_14-24](https://user-images.githubusercontent.com/16397960/105682967-1836d580-5f19-11eb-8809-7aeb766625bb.png)

**Comment by lalc** [comment]
@darkchylde, On some discussions with iOS side, we thought its safer to add the organisation name just under the logo. @josmilan Ok?

**Comment by josmilan** [comment]
@lalc @darkchylde so we need a logo, org name below the logo, and connect button, and a close. Nothing else needed right?

**Comment by lalc** [comment]
That’s right 🙏
