### ISSUE TITLE
App crashes if removed organization after accepting data agreement

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#86]
The app crashes on removing organization after accepting data agreement.

**Comment by josmilan** [comment]
Great test case. That was due to when the issued credential reaches in polling, the connection got deleted. So we cannot save the certificate. fixed the issue. we will save only if the connection is existing when credentials issued

**Comment by darkchylde** [comment]
@josmilan Can you push the code? I can check and close it.
