### ISSUE TITLE
Logo not shown in connection popup

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#96]
Logo is not shown in connection popup and data card, but works fine inside org details.

**Comment by josmilan** [comment]
<img width="602" alt="Screen Shot 2021-02-08 at 6 13 04 AM" src="https://user-images.githubusercontent.com/20550674/107164420-f176a580-69d4-11eb-8ffa-d68242981581.png">
in invitation image url coming as null

**Comment by darkchylde** [comment]
@josmilan Interesting, it works for me now.
